-- Supabase Schema for ZAYLOW / LABEL Application

-- 1. Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  customer_name TEXT NOT NULL,
  house_name TEXT,
  area TEXT,
  city TEXT,
  state TEXT,
  pincode TEXT,
  mobile TEXT,
  payment_type TEXT NOT NULL,
  cod_amount NUMERIC,
  courier TEXT,
  product_name TEXT,
  product_id TEXT,
  inventory_id TEXT,
  carton_id TEXT,
  status TEXT NOT NULL,
  tracking_id TEXT,
  shipping_label_url TEXT,
  delivered_date TIMESTAMP WITH TIME ZONE,
  warranty_start TIMESTAMP WITH TIME ZONE,
  warranty_end TIMESTAMP WITH TIME ZONE,
  return_reason TEXT,
  remarks TEXT,
  claim_date TIMESTAMP WITH TIME ZONE,
  claim_reason TEXT,
  claim_status TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Inventory Batches
CREATE TABLE IF NOT EXISTS inventory_batches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  arrival_date TIMESTAMP WITH TIME ZONE NOT NULL,
  supplier_name TEXT,
  supplier_phone TEXT,
  supplier_gst TEXT,
  supplier_address TEXT,
  invoice_no TEXT,
  po_no TEXT,
  product_name TEXT NOT NULL,
  sku TEXT,
  total_cartons INTEGER DEFAULT 0,
  pieces_per_carton INTEGER DEFAULT 0,
  total_pieces INTEGER DEFAULT 0,
  total_order_value NUMERIC,
  freight_cost NUMERIC,
  other_charges NUMERIC,
  total_landed_cost NUMERIC,
  price_per_piece NUMERIC,
  landed_cost_per_piece NUMERIC,
  remarks TEXT,
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Returns
CREATE TABLE IF NOT EXISTS returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  week_label TEXT NOT NULL,
  date_received TIMESTAMP WITH TIME ZONE NOT NULL,
  order_id TEXT,
  customer TEXT,
  mobile TEXT,
  product TEXT,
  product_id TEXT,
  return_reason TEXT,
  courier TEXT,
  tracking_id TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Stock Summary
CREATE TABLE IF NOT EXISTS stock_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name TEXT NOT NULL,
  sku TEXT,
  total_in INTEGER DEFAULT 0,
  sold INTEGER DEFAULT 0,
  returned INTEGER DEFAULT 0,
  available INTEGER DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
